x-postgres: &postgres
  image: postgres:14.5-alpine
  healthcheck:
    test: ['CMD-SHELL', 'pg_isready -U postgres -d $${POSTGRES_DB} -h 127.0.0.1']
    interval: 1s
    timeout: 2s
    retries: 20
    start_period: 2s

services:
  dev:
    <<: *postgres
    ports:
      - '5442:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ticket_board_dev

  test:
    <<: *postgres
    ports:
      - '5443:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ticket_board_test
