import {
  RiAddLine,
  RiAlertLine,
  RiArrowDropDownLine,
  RiArrowUpDownLine,
  RiChat1Line,
  RiCheckboxBlankLine,
  RiCheckboxFill,
  RiCheckLine,
  RiCircleLine,
  RiCloseLine,
  RiCloudOffLine,
  RiErrorWarningLine,
  RiEyeLine,
  RiEyeOffLine,
  RiHome2Line,
  RiImage2Line,
  RiInformation2Line,
  RiLoader2Line,
  RiLoader4Line,
  RiLoader5Line,
  RiLogoutBoxRLine,
  RiLoopRightLine,
  RiRadioButtonLine,
  RiSearch2Line,
  RiSortAsc,
  RiSortDesc,
  RiStarFill,
  RiStarHalfLine,
  RiStarLine,
  RiSubtractLine,
  RiUpload2Line,
  RiUserLine,
} from 'react-icons/ri';

export const FaIcon = {
  ArrowDropDown: RiArrowDropDownLine,
  Circle: RiCircleLine,
  CircleFill: RiRadioButtonLine,
  Chat: RiChat1Line,
  Check: RiCheckLine,
  CheckboxEmpty: RiCheckboxBlankLine,
  CheckboxFill: RiCheckboxFill,
  Close: RiCloseLine,
  CloudOff: RiCloudOffLine,
  FileUpload: RiUpload2Line,
  FlashAlert: RiAlertLine,
  FlashInfo: RiInformation2Line,
  FlashSuccess: RiCheckLine,
  FlashWarning: RiErrorWarningLine,
  Home: RiHome2Line,
  Image: RiImage2Line,
  LoaderCircle: RiLoader4Line,
  LoaderCog: RiLoader2Line,
  LoaderSpinner: RiLoader5Line,
  LoaderSync: RiLoopRightLine,
  PasswordHide: RiEyeOffLine,
  PasswordShow: RiEyeLine,
  Search: RiSearch2Line,
  SignOut: RiLogoutBoxRLine,
  SortAsc: RiSortAsc,
  SortDesc: RiSortDesc,
  SortUpDown: RiArrowUpDownLine,
  Star: RiStarLine,
  StarFull: RiStarFill,
  StarHalf: RiStarHalfLine,
  StepperMinus: RiSubtractLine,
  StepperPlus: RiAddLine,
  User: RiUserLine,
};
